apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "sample-chart.name" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sample-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sample-chart.name" . }}
    spec:
      containers:
        - name: {{ include "sample-chart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
