# Sample Kaniko workflow for building and pushing the sample Python app
name: Kaniko Action Workflow Test

on:
  workflow_dispatch:

jobs:
  kaniko-build-push:
    uses: girishcodealchemy/gh-actions-alchemy/.github/workflows/kaniko-gcp-nonprod.yml@main
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      runner: nonprod-linux-x64-medium
      workingDirectory: sample-python-app
      environment: nonprod
      dockerfile: sample-python-app/Dockerfile
      context: sample-python-app
      registry: gcr.io/YOUR_PROJECT_ID
      image: sample-python-app
      tag: latest
      push: 'true'
